version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.111 #Local ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "evt__events:1:1:compact,evt__location:1:1:compact,post__notifications:1:1,mail__notifications:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-data:
    build: ./mongo
    links:
      - mongodb
  main:
    build: .
    command: npm run app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      KAFKA_HOST: 192.168.1.111
      KAFKA_PORT: 9092
  processor:
    build: .
    command: npm run processor
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      KAFKA_HOST: 192.168.1.111
      KAFKA_PORT: 9092
  location:
    build: .
    command: npm run location
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      KAFKA_HOST: 192.168.1.111
      KAFKA_PORT: 9092
  post_deliver:
    build: .
    command: npm run post_deliver
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      KAFKA_HOST: 192.168.1.111
      KAFKA_PORT: 9092
  mail_deliver:
    build: .
    command: npm run mail_deliver
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      KAFKA_HOST: 192.168.1.111
      KAFKA_PORT: 9092